#!/usr/bin/env python

###########################################################################
#
# $Id: cpia-control,v 1.1 2002/10/13 17:05:47 duncan_haldane Exp $
#
# Copyright (C) 2000, Peter Pregler (Peter_Pregler@email.com)
#                     
###########################################################################
#
#  $Revision: 1.1 $
#  $Date: 2002/10/13 17:05:47 $
#  $Author: duncan_haldane $
#  Created by: Peter Pregler.
#
###########################################################################
#
# Description:
#    Usage and command line parsing.
#
###########################################################################

###########################################################################
#
# imported modules
#
###########################################################################

import getopt, string, sys
import cpia_control, libcpia


###########################################################################
#
# usage
#
###########################################################################

def usage():
    print ('Usage: '+sys.argv[0]+' [-hd] [proc-file]')


###########################################################################
#
# command line and options processing
#
###########################################################################

try:
    optlist, args = getopt.getopt(sys.argv[1:], 'hd')

except (getopt.error, val):
    usage()
    print (' '+val)
    sys.exit(1)

for opt in optlist:
    if(opt[0]=='-h'):
        usage()
        sys.exit(1)
    if(opt[0]=='-d'):
        cpia_control.cpia_debug=1
        
if len(args)>1:
    usage()
    sys.exit(1)

try:
    if len(args)==0:
        camera=libcpia.status()
    else:
        camera=libcpia.status(args[0])
    cpia_control.main(camera)
except (libcpia.OPEN_ERROR, name):
    print ('cannot open: '+name)
    sys.exit(2)

sys.exit(0)
